// ESLint 9 flat config：只守稳定性底线（未定义变量 = 真 bug），
// 不引入风格规则，避免存量代码大规模噪音。
import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        // 浏览器环境（app.js 在浏览器跑）
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        location: "readonly",
        history: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        fetch: "readonly",
        EventSource: "readonly",
        URLSearchParams: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        FormData: "readonly",
        FileReader: "readonly",
        Blob: "readonly",
        URL: "readonly",
        TextDecoder: "readonly",
        TextEncoder: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        console: "readonly",
        crypto: "readonly",
        CustomEvent: "readonly",
        MouseEvent: "readonly",
        KeyboardEvent: "readonly",
        PointerEvent: "readonly",
        DragEvent: "readonly",
        ClipboardEvent: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLImageElement: "readonly",
        HTMLFormElement: "readonly",
        HTMLSelectElement: "readonly",
        NodeList: "readonly",
        Element: "readonly",
        Node: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        ResizeObserver: "readonly",
        Image: "readonly",
        Audio: "readonly",
        SpeechSynthesis: "readonly",
        performance: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        Notification: "readonly",
        structuredClone: "readonly",
        Headers: "readonly",
        SpeechSynthesisUtterance: "readonly",
      },
    },
    rules: {
      // 稳定性底线：引用未定义变量 = 白屏级 bug
      "no-undef": "error",
      // 存量代码未用的变量/参数很多，先 warn 不阻塞；下划线开头是 catch 参数惯例
      "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_", "caughtErrorsIgnorePattern": "^_" }],
      "no-empty": "warn",
      "no-constant-condition": "warn",
    },
  },
  {
    ignores: ["app.js", "node_modules/"],
  },
];
